language: minimal
before_deploy:
- mkdir -p /tmp/addon/Banker
- cp -R . /tmp/addon/Banker
- rm -rf /tmp/addon/Banker/.git /tmp/addon/Banker/.travis /tmp/addon/Banker/*.md
- pushd /tmp/addon && zip -r /tmp/Banker.zip Banker && popd
addons:
  apt:
    packages:
    - zip
deploy:
  provider: releases
  api_key:
    secure: oYDIBXgYzQyg5cR6Vh8UYbd6i9aGLI6HlPwgTY1/ue+WK4+1VSOPufVSmL+vsQhC8ebnu/P32HFPUNf2RbH9yM/E7we+Cb4gYHQlCHlauqVH6wnVQWnN9Y4XsqBsK/BGs9r5jAFPP4nAvsFPGbSZcYH9Ez2Kb5sXJntldXpiB2krkUSWQZuo86ZMJPOu+xTyhxGFCsNtxlGTAi6G/MsVlbRio/UXPZTx7Gbmj1Qwtyb1UFVoZYG17IfFKftigRduw6Gaf+z9B4JEqiB/womOL4Ar9OSX4nrxG1lzbpxlj06aZkSjJYOHT8NkTq8eliwEoujB24UkUcFroVLscWL9KFs9S6zyRJnfyvXmmFIG3sA3tRyL23RMryy60TzTKopZp3NNm5RsYmlSgNGy+Or1reWibZepjgxS2gmMlWxH8yUCblgWnkUp4zyqyTuP3kTyVb+vn05bkSo2EBsVJU5/dm4xFtXqluyPaJsGZK4c7j2jpn/dT0KZ5EUE+LVq59x9rpM19s3fjtXj8Gag3xQmfr1DgHTrj/wJDaBA1d+zgaoTdju4gsVPeQkuFvj8889nRebyr7hvIIWJnY47hD5fNJTHW6ueYyAM0V2r6Oe1o8YQa1PXdiL78qBlOlAJUS/Y7IZpX1sbG9J0TBm7jhwNmI05cYgwQQ3QhJHAU5yPqAs=
  file: "/tmp/Banker.zip"
  on:
    repo: Nols1000/Banker
    tags: true
env:
  global:
    secure: vUnpHQZypkb2k8fcj0ATUhaWkoWogk4ybHfAeKDoOabCIbjkHg0C0jdjZDl9tEB+lsnTnztQ7sLfXrJx0Igb8KzjOeNrOOtBPQF9nbVsaTphVew97dcnYr6FlgrKJP4VF1D0z5cMtW7PEidvjY9k59wtNWyon/Q4s0JA3GZJ4r0bMRxLm4ZCzOaGlsYVqj7oBO8Qb/1NLWpRmnZa8ma2Kx4Bio25GaAFzfsrS1LOPFiGcD3W/jsNs3WL8vUAoJJWXQDEx2QUb6DfJDNmfEONdnDF/8n8/SG6X49/nj9vKvjhmJ9LCkEw5TGwnTSlaScSA3HPLkqLwtLEJTaq+IZSP1bP6Y3ohg3sTHk0iyGtZTmK2ETANhmxQOYjm16dwO0NtgZJ3V07SI5p8/zIfqVWRG4SOGvP6mGOXkDpaDDt6Ky5ceLugPLqlzsdDlc2RiwM+sFC7SqE1wUI+5vFkqLO6dBRMHMvIQFp+t21vE+nKLUDVtC1kYB0wnmLfWzSlJ0+oHveZ4j1tzp6rL7mSbeE4CNTmBHlhWzcKLS5+dT4Z82yJ0jt0Qz9DYlc5D0i9a62flAfTmgZJ9R19XuyvcXbfDSS90G6wyAkmhvXCsMNwZjSVFCfw3uc5fL2eArTAgpNc4FhdOyb6l1X/DTNyySVnfIApn9FIuePWrCRTXJyvKw=
