ZO_CreateStringId("SI_BANKER_NAME",										        "Bankier")
ZO_CreateStringId("SI_BANKER_HEADER_SETTINGS",									"Beschreibung")
ZO_CreateStringId("SI_BANKER_HEADER_ITEM_TYPES",								"ItemTypen")
ZO_CreateStringId("SI_BANKER_WARNING_ITEM_TYPES",								"Stelle auf Ein um Items von diesem Typ automatisch in die Bank zu transferieren,falls das Item schon in der Bank liegt.")
ZO_CreateStringId("SI_BANKER_DESC_MAIN_TITLE",									"Beschreibung")
ZO_CreateStringId("SI_BANKER_DESC_MAIN",										"Banker ist eine Mod, die dir hilft dein Inventar aufzur\195\164umen.Daf\195\188 r werden Items in deine Bank verschoben, die bereits vorhanden sind.")
ZO_CreateStringId("SI_BANKER_HEADER_DEVELOPER",									"Entwickler Einstellung")
ZO_CreateStringId("SI_BANKER_ITEMTYPE_TITLE",									"Itemtype")
ZO_CreateStringId("SI_BANKER_ITEMTYPE_DESC",									"Itemtype Description")
ZO_CreateStringId("SI_BANKER_TITLE_DEBUG",										"Zeige Debug-Informationen")
ZO_CreateStringId("SI_BANKER_COMMON_TITLE",										"Allgemeine Einstellungen")
ZO_CreateStringId("SI_BANKER_COMMON_DESC",										"")
ZO_CreateStringId("SI_BANKER_WARNING_DEVELOPER",								"Wenn du nicht wei�t was diese Option macht, dann lass die Finger davon.")
ZO_CreateStringId("SI_BANKER_MIN_TITLE",										"Gold Minimum")
ZO_CreateStringId("SI_BANKER_STEP_TITLE",										"Schritt")
ZO_CreateStringId("SI_BANKER_EITEMS_TITLE",										"Item-Transfer")
ZO_CreateStringId("SI_BANKER_EMONEY_TITLE",										"Money-Transfer")
ZO_CreateStringId("SI_BANKER_MSG_TITLE",										"Zeige Chat-Nachrichten")
ZO_CreateStringId("SI_BANKER_DEBUG_TITLE",										"Zeige Debug-Nachrichten")
ZO_CreateStringId("SI_BANKER_KB_TITLE",											"Zeige Shortcut")
ZO_CreateStringId("SI_BANKER_KB_SYNC_ITEMS",									"Synchronisiere Bank und Tasche")
ZO_CreateStringId("SI_BANKER_KB_SAFE_MONEY",									"Geldeinzahlen")
ZO_CreateStringId("SI_BINDING_NAME_SYNC_INVENTORY",     			        	"Synchronisiere Bank und Tasche")
ZO_CreateStringId("SI_BINDING_NAME_AUTO_DEPOSIT_MONEY", 				    	"Geldeinzahlen")