ZO_CreateStringId("SI_BANKER_NAME",										        "Banker")
ZO_CreateStringId("SI_BANKER_HEADER_SETTINGS",									"Description")
ZO_CreateStringId("SI_BANKER_HEADER_ITEM_TYPES",								"Filter by item types")
ZO_CreateStringId("SI_BANKER_WARNING_ITEM_TYPES",								"If this is true it will transfer automatic items from your inventory to your bank.")
ZO_CreateStringId("SI_BANKER_DESC_MAIN_TITLE",									"Description")
ZO_CreateStringId("SI_BANKER_DESC_MAIN",										"Banker helps you to keep your inventory clean.")
ZO_CreateStringId("SI_BANKER_HEADER_DEVELOPER",									"Developer Settings")
ZO_CreateStringId("SI_BANKER_ITEMTYPE_TITLE",									"Itemtype")
ZO_CreateStringId("SI_BANKER_ITEMTYPE_DESC",									"Filter which item types should be tranferd to your bank.")
ZO_CreateStringId("SI_BANKER_TITLE_DEBUG",										"Show Debug-Information")
ZO_CreateStringId("SI_BANKER_COMMON_TITLE",										"Common Settings")
ZO_CreateStringId("SI_BANKER_COMMON_DESC",										"")
ZO_CreateStringId("SI_BANKER_WARNING_DEVELOPER",								"Do not change anything here, unless you know what you do.") -- Sorry for my bad english
ZO_CreateStringId("SI_BANKER_MIN_TITLE",										"Gold-Minimum")
ZO_CreateStringId("SI_BANKER_STEP_TITLE",										"Step")
ZO_CreateStringId("SI_BANKER_EITEMS_TITLE",										"Item-Transfer")
ZO_CreateStringId("SI_BANKER_EMONEY_TITLE",										"Money-Transfer")
ZO_CreateStringId("SI_BANKER_MSG_TITLE",										"Show Chat-Messages")
ZO_CreateStringId("SI_BANKER_DEBUG_TITLE",										"Show Debug-Messages")
ZO_CreateStringId("SI_BANKER_KB_TITLE",											"Show Shortcut")
ZO_CreateStringId("SI_BANKER_KB_SYNC_ITEMS",									"Transfer Items")
ZO_CreateStringId("SI_BANKER_KB_SAFE_MONEY",									"Deposit Gold")
ZO_CreateStringId("SI_BINDING_NAME_SYNC_INVENTORY",     	    				"Transfer Items")
ZO_CreateStringId("SI_BINDING_NAME_AUTO_DEPOSIT_MONEY", 					    "Deposit Gold")